### ISSUE TITLE
GitHub Action failure

### ISSUE THREAD

**Issue by prajakta-gokhale** [ros-security/aws-oncall#18]
GitHub Action `setup-ros2 (ubuntu)` is failing on for multiple repos

* [file_talker](https://github.com/ros-tooling/file_talker/runs/333710571)
* [system_metrics_collector](https://github.com/ros-tooling/system_metrics_collector/runs/333706751)
* [cross_compile](https://github.com/ros-tooling/cross_compile/runs/333707991)
* [launch_ros_sandbox](https://github.com/ros-security/launch_ros_sandbox/runs/333709686)

Error:
```bash
E: Failed to fetch https://packages.microsoft.com/repos/microsoft-ubuntu-bionic-prod/dists/bionic/main/binary-amd64/Packages.bz2  File has unexpected size (83490 != 82014). Mirror sync in progress? [IP: 40.76.35.62 443]
   Hashes of expected file:
    - Filesize:82014 [weak]
    - SHA512:e04c3f3e0bc4b4111fc4ab70a37c21d3dc9ee546c1873cb97b24c831d0b46638d94d53e7a47897af75e57714153519117e9f4e7bdf91a69cbac26ff5978e8d05
    - SHA256:df69cd759faab94950748436a4338677a2119d232381455d87b57568b3b4f3b2
    - SHA1:4d05b812359ba0e2b879ed1d8ac94dea49066ae2 [weak]
    - MD5Sum:7073fc61f782f5e25dcdc34f9a99e2d5 [weak]
   Release file created at: Tue, 26 Nov 2019 05:04:45 +0000
E: Some index files failed to download. They have been ignored, or old ones used instead.
##[error]The process 'sudo' failed with exit code 100
##[error]Node run failed with exit code 1
```

**Comment by thomas-moulard** [comment]
@prajakta-gokhale I restarted the builds, seems like GitHub was refreshing the repos when the build started. ros-tooling/setup-ros2#25 could solve those issues, but we don't need to prioritize this now.

**Comment by prajakta-gokhale** [comment]
Builds are green now.
