### ISSUE TITLE
Add vale linter

### ISSUE THREAD

**Issue by thomas-moulard** [ros-security/aws-oncall#32]
See original issue for context https://github.com/ros-tooling/action-ros2-ci-template/issues/3

**Comment by piraka9011** [comment]
Packages to update:

* [x] [ros-tooling/system_metrics_collector](https://github.com/ros-tooling/system_metrics_collector/)
* [ ] [ros-tooling/cross_compile](https://github.com/ros-tooling/cross_compile)
* [ ] [ros-tooling/file_talker](https://github.com/ros-tooling/file_talker)
* [ ] [ros-security/launch_ros_sandbox](https://github.com/ros-security/launch_ros_sandbox)

**Comment by piraka9011** [comment]
Added Vale Linter to all owned repos.
