### ISSUE TITLE
system_metrics_collector CodeCov GitHub action is failing

### ISSUE THREAD

**Issue by prajakta-gokhale** [ros-security/aws-oncall#48]
In `system_metrics_collector` repo the CodeCov GitHub Action is failing with this error:

```bash
==> Reading reports
    - file not found at ros2_ws/lcov/total_coverage.info
--> No coverage data found.
    Please visit http://docs.codecov.io/docs/supported-languages
    search for your projects language to learn how to collect reports.
##[error]Codecov failed with the following error: The process 'bash' failed with exit code 1
##[error]Node run failed with exit code 1
```

Full build log [here](https://github.com/ros-tooling/system_metrics_collector/commit/9a51d68954dc2341b88681613485904a573c91d8/checks?check_suite_id=394951425).

**Comment by prajakta-gokhale** [comment]
From the `action-ros2-ci` log in the same run:

```bash
colcon lcov-result --packages-select system_metrics_collector
Starting >>> system_metrics_collector
--- stderr: system_metrics_collector
geninfo: ERROR: cannot write to directory /home/runner/work/system_metrics_collector/system_metrics_collector/ros2_ws/src/system_metrics_collector/system_metrics_collector/src/system_metrics_collector/system_metrics_collector!
---
Finished <<< system_metrics_collector [0.24s]
[1.915s] ERROR:colcon.colcon_lcov_result.verb.lcov_result:No valid coverage.info files found. Did you run tests?

Summary: 1 package finished [1.29s]
  1 package had stderr output: system_metrics_collector
```

**Comment by mm318** [comment]
We can try to install `colcon-python-setup-py` 0.2.3 via `pip3` as a test.

Using `apt` will only get us 0.2.2 and that's a known problematic version.

**Comment by thomas-moulard** [comment]
Data point: `ros-action-ci` is still generating `*.gcda` files correctly. https://github.com/ros-tooling/action-ros-ci/runs/383884862

**Comment by prajakta-gokhale** [comment]
Fixing bug found it `action-ros-ci` so the latest vesion can be used.

* [ ] https://github.com/ros-tooling/action-ros-ci/pull/59
* [ ] https://github.com/ros-tooling/system_metrics_collector/pull/70

**Comment by piraka9011** [comment]
From @prajakta-gokhale 
> The root of the problem is that `colcon clove-result` is not run from the right directory. This is from the test debug log: 
```
ERROR: cannot write to directory /home/runner/work/action-ros-ci/action-ros-ci/ros_ws/src/osrf_testing_tools_cpp/osrf_testing_tools_cpp/src/osrf_testing_tools_cpp/osrf_testing_tools_cpp!
```
>src/osrf_testing_tools_cpp/osrf_testing_tools_cpp gets appended twice in the path
>Next step is to figure out which directory GH Action is running the command from
>So I have added `pwd`to the commandPrefix to see that. The other thing to try is passing an empty string to commandPrefix and see if that works

**Comment by piraka9011** [comment]
I was able to reproduce locally. A warning to note when running `colcon test...` is

```
WARNING:colcon.colcon_mixin.mixin.mixin_argument:Mixin 'coverage-gcc' is not available for 'test'
```

Not sure if the mixin was never installed or if we need to add it somewhere.

**Comment by piraka9011** [comment]
Running the following command in `<root_ws>/build/system_metrics_collector` results in a successfull coverage report being generated:

```bash
 lcov --gcov-tool $(which gcov) \
  --base-directory $HOME/workspaces/ros2_master_ws/src/ros-tooling/system_metrics_collector \
  --capture \
  --directory . \
  --output-file test.txt \
  --config-file lcovrc \
```

When running

```bash
colcon lcov-result --packages-select system_metrics_collector --event-handlers console_direct+
```

I get 

```bash
geninfo: ERROR: cannot write to directory /home/ANT.AMAZON.COM/allabana/workspaces/ros2_master_ws/src/ros-tooling/system_metrics_collector/system_metrics_collector/src/ros-tooling/system_metrics_collector/system_metrics_collector
```

It looks like the [base-directory](https://github.com/colcon/colcon-lcov-result/blob/42bc4249ba159a3e30e478fbb708064e218e9cea/colcon_lcov_result/task/lcov.py#L63) argument isn't correct.

```bash
[2.916s] DEBUG:colcon.colcon_core.event_handler.log_command:
Invoking command in 'src/ros-tooling/system_metrics_collector/system_metrics_collector':
/usr/bin/lcov --gcov-tool /usr/bin/gcov 
--base-directory src/ros-tooling/system_metrics_collector/system_metrics_collector 
--capture 
--directory /home/ANT.AMAZON.COM/allabana/workspaces/ros2_master_ws/build/system_metrics_collector 
--output-file /home/ANT.AMAZON.COM/allabana/workspaces/ros2_master_ws/build/system_metrics_collector/coverage.info 
--config-file /home/ANT.AMAZON.COM/allabana/.local/lib/python3.6/site-packages/colcon_lcov_result/verb/configuration/lcovrc
```

**Comment by piraka9011** [comment]
It looks like dropping the `colcon-core` version from 0.5.2 to 0.4.3 seems to fix the problem where `colcon lcov-result` runs successfully. 

It looks like the command is correctly executed in the proper directory:

```bash
[1.857s] DEBUG:colcon.colcon_core.event_handler.log_command:
Invoking command in '/home/ANT.AMAZON.COM/allabana/workspaces/ros2_master_ws/src/ros-tooling/system_metrics_collector/system_metrics_collector': 
/usr/bin/lcov --gcov-tool /usr/bin/gcov 
--base-directory /home/ANT.AMAZON.COM/allabana/workspaces/ros2_master_ws/src/ros-tooling/system_metrics_collector/system_metrics_collector 
--capture 
--directory /home/ANT.AMAZON.COM/allabana/workspaces/ros2_master_ws/build/system_metrics_collector 
--output-file /home/ANT.AMAZON.COM/allabana/workspaces/ros2_master_ws/build/system_metrics_collector/coverage.info 
--config-file /home/ANT.AMAZON.COM/allabana/.local/lib/python3.6/site-packages/colcon_lcov_result/verb/configuration/lcovrc
```

**Comment by piraka9011** [comment]
Latest requirements.txt that works:

```
```

**Comment by piraka9011** [comment]
A solution has been implemented [here](https://github.com/colcon/colcon-lcov-result/pull/11).
In the meantime, we will lock down colcon versions in the `setup-ros` action to avoid upstream breakage.

PRs to fix:
* [x] https://github.com/ros-tooling/setup-ros/pull/46
* [ ] https://github.com/ros-tooling/action-ros-ci/pull/63
* [ ] https://github.com/ros-tooling/system_metrics_collector/pull/78

**Comment by zmichaels11** [comment]
All required PRs have been merged.
