### ISSUE TITLE
Use relative style links to declutter the README

### ISSUE THREAD

**Issue by prajakta-gokhale** [ros-security/aws-oncall#49]
Originally suggested by @piraka9011 in this [PR comment](https://github.com/ros-security/aws-oncall/pull/47#pullrequestreview-341465460).

Use relative style links to declutter the README build badge dashboard.

Example:
```md
[![Build Status][colcon-sanitizer-reports-badge]]
...
[colcon-sanitizer-reports-badge]: https://dev.azure.com/osrf/colcon-sanitizer-reports/_apis/build/status/colcon.colcon-sanitizer-reports?branchName=master
```

**Comment by zmichaels11** [comment]
Open PR: https://github.com/ros-security/aws-oncall/pull/56
Awaiting approval
